<template>
  <artistdetails
    artist-name="Marvin Jam"
    image="marvin1.jpg"
    location="Berlin, Germany"
    aliases="Marvin Jam"
    :images="['marvin1.jpg', 'marvin2.jpg', 'marvin3.jpg', 'marvin4.jpg']"
    :qanda="[ { question: 'When and why did you enter the music industry?', answer: 'I moved to Berlin 13 years ago and had no idea about Cosmos Night Club. After 2 years I found my way as a guest to the clubs and festivals and after a while, I started to play there with my Funckband. I guess as a musician/ singer, there is no way to not get in touch with the electronic music scene in Berlin.' }, { question: 'Who/What is your biggest inspiration?', answer: 'Life itself, I would say. In these days, everything and everyone connected to a conscious way of life, body soul and spirit. My mum was and is a big inspiration for me, as well as my wife and friends. On a musical level, I found my inspiration in HipHop/ RnB, old Soul- Funk and Blues. And also Artists of my early days like Prince, D\'Angelo and Lenny Kravitz inspired me as a singer. In the electronic music scene it was the Berlin club sound in general. Or for example, the first tack I fell in love with, was Solomun\'s Love Recycled 2 and for sure liveacts like DoP.' }, { question: 'We all know the negative sides of COVID-19 to the music industry, but what are the positive sides you are getting out of it in life and music?', answer: 'Almost everything has something positive in it. At the beginning of the pandemic,  I enjoyed the time to myself, with inner engineering, changed some habits and built up new routines in my life. I enjoyed and still enjoy to work in the studio, but I  felt less pressure when everything slowed down. It was a time to figure out stuff and put myself in order.' }, { question: 'What are the biggest obstacles you find as a DJ/producer based in Berlin?', answer: 'I\'ve always been my biggest Obstacle, which has different reasons. One was to make decisions, to decide something. But I freed myself more or less from that and I\'m doing better and better everyday. I guess for me, there is no obstacle which is not on my responsibility at the end. So today, I would say, it\'s how I feel sometimes, the attitude, discipline and faith that comes with it.' }, { question: 'Tell us about your future projects, is there something exciting to come?', answer: 'Last year I worked on my DJ skills, combined with my vocal elements and my sound in general to a more advanced level. Now im focusing more on creating music. For sure clubmusic will always be part of it, but I want to focus more on other stuff too and still have to figure out how that works or how I\'m able to combine it. At the moment I have to finish some projects for different producers and collaborations. After that I\'ll go back to my stuff, like projects I do on my own or with friends and producers I chose to work with. So, yeah there is definitely some exciting music to come!' } ]"
    soundcloud="https://soundcloud.com/marvin-jam/soundity-livestream"
    facebook="https://www.facebook.com/MarvinJam333/about"
    instagram="https://www.instagram.com/marvin_jam333"
  >
    What the world means to Marvin Jam may be compared to a child in a candy shop. And as we all know, you can stare at all the enticements for as long as you want to, in the end you have to decide and find which one will be yours. Fortunately his liberal spirit made Marvin choose electronic music and he finally found his own way after being part of several projects and Combos.<br><br>
    Marvin performs his outstanding, groovy sound and sets in combination with his excellent singing. Enjoying and enhancing many clubs and festivals like Sisyphos, Kater, Fusion or Feel Festival with his funkband, he began to join and support different DJs, so as well Live-Acts.<br><br>
    Today he’s creating tracks on his own or in cooperation with different producers.
    Emancipating himself to a solo-artist and as a DJ, his incredible tunes create an unique sound including different genres and of course featured by his lovely voice.
    And if there’s one clean sign, is that this Dude got Taste & Style.
  </artistdetails>
</template>
