name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run initializing script
        run: COMPONENT_API=${{ matrix.api }} ./init.sh

      - run: yarn install

      - name: Run lint
        run: yarn lint

      - name: Run static site generation
        run: yarn generate

      - name: Copy CNAME
        run: cp CNAME ./dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
